name: Deploy to AWS

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_KEY }} # GitHub Secrets에 등록한 AWS 서버의 SSH 키

      - name: Deploy to AWS Server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@43.203.122.230 << 'EOF'
          cd /home/ubuntu/meeting-coach-be
          git pull origin main
          pnpm install
          pm2 restart server.js --name meeting-coach-be
          EOF
