name: Deploy to AWS

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create PEM file
        run: |
          echo "${{ secrets.MEETING_COACH_PEM_KEY }}" > ./meeting_coach_key.pem
          chmod 400 ./meeting_coach_key.pem

      - name: Deploy to AWS Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ./meeting_coach_key.pem ubuntu@43.203.122.230 << 'EOF'
          cd /home/ubuntu/meeting-coach-be
          git pull origin main
          pnpm install
          pm2 restart server.js --name meeting-coach-be
          EOF
