name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create PEM file
        run: |
          echo "${{ secrets.TEMP_PEM }}" > ./temp.pem
          chmod 400 ./temp.pem

      - name: Deploy to AWS Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ./temp.pem ubuntu@43.200.254.240 << 'EOF'
          cd /home/ubuntu/nodejs
          git pull origin main
          pnpm install
          pm2 start nodejs
          EOF
